name: project-dependencies
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.7.0
  - torchvision>=0.8.1
  - pillow>=8.4.0
  - numpy>=1.22.3
  - matplotlib>=3.3.2
  - scikit-learn
  - opencv
  - tensorflow>=2.5.0
  - tqdm